stateDiagram
    [*] --> SplashScreen
    SplashScreen --> TabsLayout
    TabsLayout --> IndexScreen
    TabsLayout --> InviteScreen
    TabsLayout --> AccountScreen
    TabsLayout --> WithdrawalOptionsScreen
    TabsLayout --> StoreDetailsScreen
    TabsLayout --> ProductsScreen
    TabsLayout --> CodesScreen
    TabsLayout --> ConditionsScreen
    TabsLayout --> HelpScreen
    TabsLayout --> SettingsScreen
    TabsLayout --> PrivacyPolicyScreen
    TabsLayout --> TermsOfUseScreen
    TabsLayout --> CampaignsScreen
    TabsLayout --> MyRequestsScreen
    TabsLayout --> RequestDetailsScreen
    TabsLayout --> RequestNotScreen
    AccountScreen --> LoginScreen
    AccountScreen --> LogoutScreen
    WithdrawalOptionsScreen --> ConditionsScreen
    StoreDetailsScreen --> ProductsScreen
    StoreDetailsScreen --> AffiliateLinkScreen
    ProductsScreen --> ProductDetailsScreen
    CodesScreen --> QRCodeScannerScreen
